export {default as App} from './App'
export {default as Login} from './Login'
export {default as HomePage} from './HomePage'
export {default as OrderList} from './Order/OrderList'
export {default as AddOrder} from './Order/AddOrder'
export * from './Delivery'
export * from './Shop'
export * from './Pickup'
